### PR TITLE
Fix thrown exception when retries != 0

### LINKED ISSUE #62: User-defined exceptions handled incorrectly with retries, may be replaced by NoServersAvailable
When the `retries` option is non-zero, an exception thrown on the server results in the client incorrectly throwing a `NoServersAvailable` exception instead of the correct exception.

With `retries` set to `0`, the correct exception is thrown:

```
/Users/div/w/web/hello_service.rb:27:in `recv_pong': bar! (Hello::BadArgumentException)
    from /Users/div/w/web/hello_service.rb:17:in `pong'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:169:in `block in handled_proxy'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:150:in `ensure_socket_alignment'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:169:in `handled_proxy'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:64:in `pong'
    from pong.rb:36:in `<main>'
```

With `retries` set to `1` or higher, this changes to the misleading exception:

```
/Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:224:in `no_servers_available!': No live servers in [127.0.0.1:10002]. (ThriftClient::NoServersAvailable)
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:145:in `next_live_server'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:101:in `connect!'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:163:in `handled_proxy'
    from /Users/div/.rvm/gems/ruby-1.9.3-p194@pagerduty/bundler/gems/thrift_client-b8ac8c65220e/lib/thrift_client/abstract_thrift_client.rb:64:in `pong'
    from pong.rb:36:in `<main>'
```

Client code:

``` ruby
require 'thrift'
require 'thrift_client'
require_relative "hello_service"

servers = ['127.0.0.1:10002']
options = {
      transport_wrapper: Thrift::FramedTransport,
      connect_timeout: 4,
      timeout: 45,
      retries: 0
}

thrift_client = ThriftClient.new(
    Hello::HelloService::Client, servers, options
)

thrift_client.pong
```

Thrift API:

```
namespace java com.example.hello
namespace rb Hello

exception BadArgumentException {
  1: string message
}

service HelloService {
  string pong() throws (1: BadArgumentException a);
}
```

This is against the `0.9.2` gem.

### PR DESCRIPTION
**Pull request by usrbincc**
Fixes #62

Haven't done a pull request in awhile (a little rusty on the protocol), but the repro code should be self-explanatory:

``` sh
#!/bin/sh
# clone
git clone https://github.com/twitter/thrift_client
cd thrift_client

# get test (based on #62's code)
GH_ISSUE=issue-62
git clone https://gist.github.com/usrbincc/f37b4f009d9ef610593a t-$GH_ISSUE

# test current master @ 5c10d5988182 (reproduce exact state)
git checkout 5c10d5988182
t-$GH_ISSUE/dotest-*

# test $GH_ISSUE
git remote add usrbincc https://github.com/usrbincc/thrift_client
git fetch usrbincc
git checkout -b $GH_ISSUE --track usrbincc/$GH_ISSUE
t-$GH_ISSUE/dotest-*
```

### CODE REVIEW

**Comment by usrbincc** [comment]
Okay, finally got around to doing a full ruby setup with rvm so I can run unit tests properly (sorry about that). I updated the pull request text to match its updated commit.

So the current behavior is preserved &mdash; try each error-throwing server at most once (not my normal definition of a retry). The exception thrown by the last server tried is rethrown.

----

There is an unrelated failing test (which also shows up in 5c10d5988182) which is fixed in #65.

**Comment by jugglinmike** [comment]
Hey @usrbincc--I've been trying to reach you regarding JSHint. Are you still receiving GitHub notifications?

**Comment by jugglinmike** [comment]
Hey @usrbincc --I've been trying to reach you regarding JSHint. Are you still receiving GitHub notifications?

**Comment by fluxusfrequency** [comment]
Closing out all old PRs to this repo. Please reopen if you'd like further consideration!

**Pull request closed without merging**
